fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

api_directory:
    resource: "@RIFileManagerBundle/Resources/config/routing/directory_routing.yml"
    prefix: '/api'

api_files:
    resource: "@RIFileManagerBundle/Resources/config/routing/file_routing.yml"
    prefix: '/api'

api_selection:
    resource: "@RIFileManagerBundle/Resources/config/routing/selection_routing.yml"
    prefix: '/api/selection'

ri_filemanager_index:
    pattern: /index
    defaults: { _controller: RIFileManagerBundle:Default:index }

ri_filemanager_page:
    pattern: /page
    defaults: { _controller: RIFileManagerBundle:Default:page }
    options:
        expose: true

ri_filemanager_tinymce:
    pattern: /tinyce
    defaults: { _controller: RIFileManagerBundle:Default:tinyMCE }

