language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - Resources/source/node_modules
    - Resources/source/bower_components
install:
  - cd Resources/source
  - npm install -g grunt-cli
  - npm i
  - grunt bower
  - grunt build
  - grunt karma-dev
