language: node_js
node_js:
  - "0.12"
cache:
  directories:
    - node_modules
    - bower_components
install:
  - cd Resources/source
  - npm install -g grunt-cli
  - npm i
  - grunt bower
  - grunt karma
